site_name: SpaceDyn User Manual

nav:
    - Top: index.md
    - Basics: basics.md
    - MATLAB: matlab.md
    - C++: c++.md
    - ROS: ros.md
    - Appendix: appendix.md

theme:
    name: readthedocs
    language: 'ja'

extra:
    search:
        language: 'jp'

extra_css:
    - "css/custom.css"

markdown_extensions:
    - meta
    - mdx_math
    - markdown_katex
#    - pymdownx.mark  # build error
#    - pymdownx.magiclink  # build error
#    - pymdownx.emoji  # build error
#    - fontawesome_markdown  # build error
#    - pymdownx.keys  # build error
#    - python-markdown-math
    - def_list
    - admonition
    - codehilite:
        linenums: true
        use_pygments: true

extra_javascript:
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
